### ISSUE TITLE
File I/O issues with Python

### ISSUE THREAD

**Issue by vritant24** [microsoft/vscode-python-web-wasm#48] opened 2023-04-06 19:29 UTC
For the following scenario:
1. open a folder in vscode.dev
2. Create a python file with the following content:
```python
with open('helloWorld.txt', 'w') as f:
    f.write("hello world")
```
This throws an error saying file not found. This is also an issue when reading files from the same directory

when adjusting the file write path:
```python
with open('/workspace/helloWorld.txt', 'w') as f:
    f.write("hello world")
```
The execution succeeds but the file isn't shown in the Explorer tree unless the browser is refreshed.

1. Is there a way to get relative paths working? (since this is what our customers will primarily need)?
2. Can the file be shown in the Explorer tree as soon as its created?

**Comment by dbaeumer** [comment] 2023-04-11 07:57
The updating of the explorer works for me:

![cast](https://user-images.githubusercontent.com/1931590/231094100-1a819c8f-4ce3-43ec-970f-04091bb845b5.gif)

If you use your own FS provider you need to provide FS events otherwise the explorer doesn't know when to update. See https://insiders.vscode.dev/github/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L8242

I will look into the relative path issue, but that might not be so easy to address.

**Comment by dbaeumer** [comment] 2023-04-11 08:38
Investigated and the reason for the relative path failure is that python starts with a working directory of '/'.

If I change the code to

```
import os
os.chdir('/workspace')

with open('helloWorld.txt', 'w') as f:
    f.write("hello world")
```

Everything works fine.

@brettcannon any tip how I can convince python to use '/workspace' as the working directory when I startup python.

**Comment by brettcannon** [comment] 2023-04-11 17:24
@dbaeumer wouldn't the WASI runtime dictate what the working directory is? Python just asks the OS, so in this case I would assume the WASI call is made (i.e., this is a duplicate of https://github.com/microsoft/vscode-python-web-wasm/issues/36 ).

**Comment by dbaeumer** [comment] 2023-04-12 05:43
@brettcannon WASI starts with the working directory of '/' and there is no API / callback in WASI that allows me to change this. And it might never be added to WASM/WASI.  See https://github.com/WebAssembly/wasi-filesystem/issues/24 for the discussion and the arguments around this. 

I never tried to use the suggestion of using '.' as a preopen directory to some sort of emulate this since I think it will have the negative side effect of making all `./*` paths go to that preopen directory regardless of whether `chdir` was called and managed in user space.

So I was hoping that we can simply do that in python because then the current working directory is managed in user space correctly.

**Comment by brettcannon** [comment] 2023-04-12 18:11
If you're willing to ship custom Python code to run at start-up, you can use `sitecustomize` (docs in the [site module](https://docs.python.org/3/library/site.html)) or [`PYTHONSTARTUP` environment variable](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSTARTUP) to execute `os.chdir()`.

**Comment by dbaeumer** [comment] 2023-04-13 06:42
@brettcannon thanks. I will experiment with them a little.

**Comment by vritant24** [comment] 2023-05-31 17:16
@dbaeumer @brettcannon I've tried using `os.chdir` but the issue exists when the file being run is in a nested directory.

for example, given the following folder structure:
```
- root/
- file1.py
- read1.txt
- dir/
   - file2.py
   - read2.txt
```

if the following is run on python startup:
```
import os
os.chdir("/root")
```

`file1.py` reading `./read1.txt` works, but `file2.py` reading `read2.txt` does not.
it seems that `os.chdir` needs to be set to the directory of the executing file to make relative paths work. Is that the expectation?

**Comment by dbaeumer** [comment] 2023-06-01 16:36
@vritant24 with the new wasm-wasi-core I release today you have the possibility to create a memory file system. So you could create the content of the file `PYTHONSTARTUP` points to every start differently without having something on disk. I use that trick for the debugger I converted. You might want to look here for an example: https://insiders.vscode.dev/github/microsoft/vscode-python-web-wasm/blob/dbaeumer/democratic-limpet-amethyst/src/common/python.ts#L87

**Comment by vritant24** [comment] 2023-06-01 17:47
That gives a way to fix the issue that works for us :) Thank you!

Feel free to close the issue if you don't see the need to keep it open

**Comment by dbaeumer** [comment] 2023-06-02 07:03
Closing the issue then. There is nothing I can except waiting for https://github.com/WebAssembly/wasi-filesystem/issues/24

**Closed by dbaeumer** 2023-06-02 07:03 UTC
